/**
 * This code was generated by Builder.io.
 */
import React from "react";

const JewelryRedefined = () => {
  return (
    <section className="flex overflow-hidden relative flex-col justify-center mt-20 w-full text-center max-w-[1440px] min-h-[270px] max-md:mt-10 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a5ecaf74ffa446d5c28200b2af4931b8e5e48dfe79c66f40274a150d3eefabb1?apiKey=04f0f0d41c7d4ab7868ce7f579c0596c&"
        alt="Jewelry Redefined background"
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative justify-center items-center px-16 py-14 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col w-96 max-w-full">
          <div className="flex flex-col px-6 py-0.5 max-w-[912px] text-zinc-800 max-md:px-5">
            <h2 className="self-center text-3xl">Jewelry Redefined</h2>
            <p className="mt-6 text-sm">
              Join us in transforming the jewelry industry for good.
            </p>
          </div>
          <button className="justify-center self-center px-7 py-px mt-10 text-sm font-medium leading-10 text-white bg-teal-900 max-md:px-5">
            Learn More
          </button>
        </div>
      </div>
    </section>
  );
};

export default JewelryRedefined;
