/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

const Header = () => (
  <header className={styles.headerWrapper}>
    <div className={styles.topBanner}>
      <div className={styles.bannerContent}>
        <div className={styles.bannerText}>
          ENDS SOON! Receive a Sapphire Necklace With Purchase Over $1,000.
        </div>
        <div className={styles.bannerIcon}>&gt;</div>
      </div>
    </div>
  </header>
);

export default Header;
