/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./HeroBanner.module.css";

const HeroBanner = () => (
  <section className={styles.bannerWrapper}>
    <div className={styles.bannerContent}>
      <img
        className={styles.bannerImage}
        loading="lazy"
        src="http://b.io/ext_46-"
        alt="Hero banner background"
      />
      <h1 className={styles.bannerTitle}>Save the Date</h1>
      <p className={styles.bannerDescription}>
        This summer, RSVP yes to a style you'll melt over.
      </p>
      <div className={styles.buttonGroup}>
        <button className={styles.primaryButton}>Shop Engagement Rings</button>
        <button className={styles.secondaryButton}>Shop Wedding Rings</button>
      </div>
    </div>
  </section>
);

export default HeroBanner;
