/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Navigation.module.css";

const Navigation = () => (
  <nav className={styles.navWrapper}>
    <div className={styles.navContent}>
      <div className={styles.contactInfo}>
        <div className={styles.phoneNumber}>650.530.1828</div>
        <div className={styles.iconWrapper}>
          <img
            className={styles.icon}
            loading="lazy"
            src="http://b.io/ext_39-"
            alt="Contact icon"
          />
        </div>
      </div>
    </div>
    <div className={styles.logoWrapper}>
      <img
        className={styles.logo}
        loading="lazy"
        src="http://b.io/ext_40-"
        alt="Company logo"
      />
    </div>
    <div className={styles.navLinks}>
      <img
        className={styles.navIcon}
        loading="lazy"
        src="http://b.io/ext_41-"
        alt="Navigation icon"
      />
      <img
        className={styles.navIcon}
        loading="lazy"
        src="http://b.io/ext_42-"
        alt="Navigation icon"
      />
      <img
        className={styles.navIcon}
        loading="lazy"
        src="http://b.io/ext_43-"
        alt="Navigation icon"
      />
      <img
        className={styles.navIcon}
        loading="lazy"
        src="http://b.io/ext_44-"
        alt="Navigation icon"
      />
      <img
        className={styles.cartIcon}
        loading="lazy"
        src="http://b.io/ext_45-"
        alt="Shopping cart"
      />
    </div>
  </nav>
);

export default Navigation;
