/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PromoBanner.module.css";

const PromoBanner = () => (
  <section className={styles.promoBannerWrapper}>
    <div className={styles.promoBannerContent}>
      <div className={styles.promoImageWrapper}>
        <img
          className={styles.promoImage}
          loading="lazy"
          src="http://b.io/ext_51-"
          alt="Promo banner"
        />
      </div>
      <div className={styles.promoTextWrapper}>
        <h3 className={styles.promoTitle}>ENDS SOON!</h3>
        <p className={styles.promoDescription}>
          Receive a Sapphire Necklace with purchase over $1,000.
        </p>
        <a href="#" className={styles.promoLink}>
          See Terms
        </a>
      </div>
    </div>
  </section>
);

export default PromoBanner;
