/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ShopByCategory.module.css";

const ShopByCategory = () => (
  <section className={styles.categoryWrapper}>
    <h2 className={styles.categoryTitle}>Shop By Category</h2>
    <div className={styles.categoryGrid}>
      <div className={styles.categoryItem}>
        <img
          className={styles.categoryImage}
          loading="lazy"
          src="http://b.io/ext_47-"
          alt="Category 1"
        />
      </div>
      <div className={styles.categoryItem}>
        <img
          className={styles.categoryImage}
          loading="lazy"
          src="http://b.io/ext_48-"
          alt="Category 2"
        />
      </div>
      <div className={styles.categoryItem}>
        <img
          className={styles.categoryImage}
          loading="lazy"
          src="http://b.io/ext_49-"
          alt="Category 3"
        />
      </div>
      <div className={styles.categoryItem}>
        <img
          className={styles.categoryImage}
          loading="lazy"
          src="http://b.io/ext_50-"
          alt="Category 4"
        />
      </div>
    </div>
  </section>
);

export default ShopByCategory;
