// <auto-generated />
using System;
using DiamondStoreSystem.DataLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiamondStoreSystem.DataLayer.Migrations
{
    [DbContext(typeof(DiamondStoreSystemDBContext))]
    [Migration("20240630141225_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Accessory", b =>
                {
                    b.Property<string>("AccessoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.HasKey("AccessoryID");

                    b.ToTable("Accessories");

                    b.HasData(
                        new
                        {
                            AccessoryID = "A1",
                            AccessoryName = "Gold Ring",
                            Block = false,
                            Brand = "GoldBrand",
                            Description = "18K gold ring",
                            Material = 1,
                            Price = 200.0,
                            SKU = "R123",
                            Style = 1,
                            UnitInStock = 10
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Account", b =>
                {
                    b.Property<string>("AccountID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoyaltyPoint")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Phone")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("WorkingSchedule")
                        .HasColumnType("int");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountID = "C1",
                            Address = "123 Main St",
                            Block = false,
                            DOB = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            Gender = 1,
                            JoinDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            LoyaltyPoint = 100,
                            Password = "741f67765bef6f01f37bf5cb1724509a83409324efa6ad2586d27f4e3edea296",
                            Phone = 1234567890m,
                            Role = 0,
                            WorkingSchedule = 1
                        },
                        new
                        {
                            AccountID = "E1",
                            Address = "123 Main St",
                            Block = false,
                            DOB = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            FirstName = "John",
                            Gender = 1,
                            JoinDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            LoyaltyPoint = 100,
                            Password = "473287f8298dba7163a897908958f7c0eae733e25d2e027992ea2edc9bed2fa8",
                            Phone = 1234567890m,
                            Role = 3,
                            WorkingSchedule = 1
                        },
                        new
                        {
                            AccountID = "E2",
                            Address = "123 Main St",
                            Block = false,
                            DOB = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnny.dang@example.com",
                            FirstName = "John",
                            Gender = 1,
                            JoinDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            LoyaltyPoint = 100,
                            Password = "473287f8298dba7163a897908958f7c0eae733e25d2e027992ea2edc9bed2fa8",
                            Phone = 1234567890m,
                            Role = 1,
                            WorkingSchedule = 1
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Diamond", b =>
                {
                    b.Property<string>("DiamondID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<double>("CaratWeight")
                        .HasColumnType("float");

                    b.Property<int>("ClarityGrade")
                        .HasColumnType("int");

                    b.Property<int>("ColorGrade")
                        .HasColumnType("int");

                    b.Property<int>("CutGrade")
                        .HasColumnType("int");

                    b.Property<double>("DepthPercent")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FluoresceneGrade")
                        .HasColumnType("int");

                    b.Property<int>("GIAReportNumber")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Inscription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LabCreated")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolishGrade")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<int>("SymmetryGrade")
                        .HasColumnType("int");

                    b.Property<double>("TablePercent")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("DiamondID");

                    b.ToTable("Diamond");

                    b.HasData(
                        new
                        {
                            DiamondID = "D1",
                            Block = false,
                            CaratWeight = 1.2,
                            ClarityGrade = 1,
                            ColorGrade = 1,
                            CutGrade = 1,
                            DepthPercent = 62.299999999999997,
                            Description = "A beautiful diamond",
                            FluoresceneGrade = 0,
                            GIAReportNumber = 123456,
                            Height = 3.5,
                            Inscription = "GIA123456",
                            IssueDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LabCreated = 0,
                            Length = 4.0,
                            Origin = "South Africa",
                            PolishGrade = 1,
                            Price = 5000.0,
                            SKU = "D123",
                            Shape = 1,
                            SymmetryGrade = 1,
                            TablePercent = 57.5,
                            Width = 4.0
                        },
                        new
                        {
                            DiamondID = "D2",
                            Block = false,
                            CaratWeight = 1.5,
                            ClarityGrade = 2,
                            ColorGrade = 2,
                            CutGrade = 2,
                            DepthPercent = 61.799999999999997,
                            Description = "Another beautiful diamond",
                            FluoresceneGrade = 1,
                            GIAReportNumber = 789012,
                            Height = 3.7999999999999998,
                            Inscription = "GIA789012",
                            IssueDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LabCreated = 1,
                            Length = 4.5,
                            Origin = "Botswana",
                            PolishGrade = 2,
                            Price = 6000.0,
                            SKU = "D456",
                            Shape = 1,
                            SymmetryGrade = 2,
                            TablePercent = 56.0,
                            Width = 4.5
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Order", b =>
                {
                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOrdered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeAssignID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PayMethod")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EmployeeAssignID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<string>("MainDiamondID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.HasIndex("AccessoryID")
                        .IsUnique();

                    b.HasIndex("MainDiamondID")
                        .IsUnique();

                    b.HasIndex("OrderID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.SubDiamond", b =>
                {
                    b.Property<string>("SubDiamondID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubDiamondID");

                    b.HasIndex("ProductID");

                    b.ToTable("SubDiamonds");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.VnPaymentResponse", b =>
                {
                    b.Property<string>("VnpOrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VnPayResponseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VnpOrderId");

                    b.ToTable("VnPaymentResponses");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Warranty", b =>
                {
                    b.Property<string>("WarrantyID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarrantyID");

                    b.ToTable("Warranties");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Order", b =>
                {
                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Account", "Customer")
                        .WithMany("OrdersCustomer")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Account", "EmployeeAccount")
                        .WithMany("OrdersStaff")
                        .HasForeignKey("EmployeeAssignID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.VnPaymentResponse", null)
                        .WithOne("Order")
                        .HasForeignKey("DiamondStoreSystem.DataLayer.Models.Order", "OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("EmployeeAccount");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Product", b =>
                {
                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Accessory", "Accessory")
                        .WithOne()
                        .HasForeignKey("DiamondStoreSystem.DataLayer.Models.Product", "AccessoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Diamond", "MainDiamond")
                        .WithOne()
                        .HasForeignKey("DiamondStoreSystem.DataLayer.Models.Product", "MainDiamondID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Warranty", null)
                        .WithOne("Product")
                        .HasForeignKey("DiamondStoreSystem.DataLayer.Models.Product", "ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("MainDiamond");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.SubDiamond", b =>
                {
                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Product", "Product")
                        .WithMany("SubDiamonds")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Diamond", "Diamond")
                        .WithOne()
                        .HasForeignKey("DiamondStoreSystem.DataLayer.Models.SubDiamond", "SubDiamondID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diamond");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Account", b =>
                {
                    b.Navigation("OrdersCustomer");

                    b.Navigation("OrdersStaff");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Product", b =>
                {
                    b.Navigation("SubDiamonds");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.VnPaymentResponse", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Warranty", b =>
                {
                    b.Navigation("Product")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
