// <auto-generated />
using System;
using DiamondStoreSystem.DataLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiamondStoreSystem.DataLayer.Migrations
{
    [DbContext(typeof(DiamondStoreSystemDBContext))]
    [Migration("20240630061555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Accessory", b =>
                {
                    b.Property<string>("AccessoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.HasKey("AccessoryID");

                    b.ToTable("Accessories");

                    b.HasData(
                        new
                        {
                            AccessoryID = "A1",
                            AccessoryName = "Gold Chain",
                            Block = false,
                            Brand = "Luxury",
                            Description = "24k Gold Chain",
                            Material = 1,
                            Price = 2000.0,
                            SKU = "ACC001",
                            Style = 1,
                            UnitInStock = 10
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Account", b =>
                {
                    b.Property<string>("AccountID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoyaltyPoint")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Phone")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("WorkingSchedule")
                        .HasColumnType("int");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountID = "C1",
                            Address = "123 Main St",
                            Block = false,
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer@example.com",
                            FirstName = "John",
                            Gender = 1,
                            JoinDate = new DateTime(2024, 6, 30, 13, 15, 55, 131, DateTimeKind.Local).AddTicks(5967),
                            LastName = "Doe",
                            LoyaltyPoint = 100,
                            Password = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            Phone = 123456789m,
                            Role = 0,
                            WorkingSchedule = 0
                        },
                        new
                        {
                            AccountID = "S2",
                            Address = "456 Elm St",
                            Block = false,
                            DOB = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@example.com",
                            FirstName = "Jane",
                            Gender = 2,
                            JoinDate = new DateTime(2024, 6, 30, 13, 15, 55, 131, DateTimeKind.Local).AddTicks(6006),
                            LastName = "Smith",
                            LoyaltyPoint = 0,
                            Password = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            Phone = 987654321m,
                            Role = 1,
                            WorkingSchedule = 0
                        },
                        new
                        {
                            AccountID = "S1",
                            Address = "456 Elm St",
                            Block = false,
                            DOB = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            FirstName = "Jane",
                            Gender = 2,
                            JoinDate = new DateTime(2024, 6, 30, 13, 15, 55, 131, DateTimeKind.Local).AddTicks(6025),
                            LastName = "Smith",
                            LoyaltyPoint = 0,
                            Password = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            Phone = 987654321m,
                            Role = 4,
                            WorkingSchedule = 0
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Diamond", b =>
                {
                    b.Property<string>("DiamondID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<double>("CaratWeight")
                        .HasColumnType("float");

                    b.Property<int>("ClarityGrade")
                        .HasColumnType("int");

                    b.Property<int>("ColorGrade")
                        .HasColumnType("int");

                    b.Property<int>("CutGrade")
                        .HasColumnType("int");

                    b.Property<double>("DepthPercent")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FluoresceneGrade")
                        .HasColumnType("int");

                    b.Property<int>("GIAReportNumber")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Inscription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LabCreated")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolishGrade")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<int>("SymmetryGrade")
                        .HasColumnType("int");

                    b.Property<double>("TablePercent")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("DiamondID");

                    b.ToTable("Diamond");

                    b.HasData(
                        new
                        {
                            DiamondID = "D1",
                            Block = false,
                            CaratWeight = 1.0,
                            ClarityGrade = 1,
                            ColorGrade = 1,
                            CutGrade = 1,
                            DepthPercent = 62.5,
                            Description = "High quality diamond",
                            FluoresceneGrade = 0,
                            GIAReportNumber = 12345,
                            Height = 5.0,
                            Inscription = "GIA12345",
                            IssueDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LabCreated = 0,
                            Length = 5.0,
                            Origin = "Africa",
                            PolishGrade = 1,
                            Price = 3000.0,
                            SKU = "DIA001",
                            Shape = 1,
                            SymmetryGrade = 1,
                            TablePercent = 55.0,
                            Width = 5.0
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Order", b =>
                {
                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOrdered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeAssignID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PayMethod")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<string>("VnpOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EmployeeAssignID");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderID = "O1",
                            Block = false,
                            CustomerID = "C1",
                            DateOrdered = new DateTime(2024, 6, 30, 13, 15, 55, 131, DateTimeKind.Local).AddTicks(6187),
                            EmployeeAssignID = "S2",
                            OrderStatus = 1,
                            PayMethod = 1,
                            TotalPrice = 5000.0
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<string>("MainDiamondID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.HasIndex("AccessoryID");

                    b.HasIndex("MainDiamondID");

                    b.HasIndex("OrderID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = "P1",
                            AccessoryID = "A1",
                            Block = false,
                            MainDiamondID = "D1",
                            OrderID = "O1",
                            Price = 5000.0
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.SubDiamond", b =>
                {
                    b.Property<string>("SubDiamondID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubDiamondID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("SubDiamonds");

                    b.HasData(
                        new
                        {
                            SubDiamondID = "D1",
                            OrderID = "O1"
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.VnPaymentResponse", b =>
                {
                    b.Property<string>("VnpOrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VnPayResponseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VnpOrderId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("VnPaymentResponses");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Warranty", b =>
                {
                    b.Property<string>("WarrantyID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WarrantyID");

                    b.HasIndex("ProductID");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            WarrantyID = "W1",
                            Block = false,
                            ExpiredDate = new DateTime(2025, 6, 30, 13, 15, 55, 131, DateTimeKind.Local).AddTicks(6289),
                            IssueDate = new DateTime(2024, 6, 30, 13, 15, 55, 131, DateTimeKind.Local).AddTicks(6288),
                            ProductID = "P1"
                        });
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Order", b =>
                {
                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Account", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Account", "EmployeeAccount")
                        .WithMany()
                        .HasForeignKey("EmployeeAssignID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("EmployeeAccount");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Product", b =>
                {
                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Accessory", "Accessory")
                        .WithMany()
                        .HasForeignKey("AccessoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Diamond", "MainDiamond")
                        .WithMany()
                        .HasForeignKey("MainDiamondID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("MainDiamond");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.SubDiamond", b =>
                {
                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Product", null)
                        .WithMany("SubDiamonds")
                        .HasForeignKey("ProductID");

                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Diamond", "Diamond")
                        .WithOne()
                        .HasForeignKey("DiamondStoreSystem.DataLayer.Models.SubDiamond", "SubDiamondID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diamond");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.VnPaymentResponse", b =>
                {
                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Order", "Order")
                        .WithOne("VnPaymentResponse")
                        .HasForeignKey("DiamondStoreSystem.DataLayer.Models.VnPaymentResponse", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Warranty", b =>
                {
                    b.HasOne("DiamondStoreSystem.DataLayer.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Account", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Order", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("VnPaymentResponse");
                });

            modelBuilder.Entity("DiamondStoreSystem.DataLayer.Models.Product", b =>
                {
                    b.Navigation("SubDiamonds");
                });
#pragma warning restore 612, 618
        }
    }
}
